config/routes.rb
# frozen_string_literal: true

require 'sidekiq_unique_jobs/web' if ENV['ENABLE_SIDEKIQ_UNIQUE_JOBS_UI'] == true
require 'sidekiq-scheduler/web'

class RedirectWithVary < ActionDispatch::Routing::PathRedirect
  def build_response(req)
    super.tap do |response|
      response.headers['Vary'] = 'Origin, Accept'
    end
  end
end

def redirect_with_vary(path)
  RedirectWithVary.new(301, path)
end

Rails.application.routes.draw do
  root 'home#index'

  mount LetterOpenerWeb::Engine, at: 'letter_opener' if Rails.env.development?

  get 'health', to: 'health#show'

  authenticate :user, ->(user) { user.role&.can?(:view_devops) } do
    mount Sidekiq::Web, at: 'sidekiq', as: :sidekiq
    mount PgHero::Engine, at: 'pghero', as: :pghero
  end

  use_doorkeeper do
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications',
                tokens: 'oauth/tokens'
  end

  namespace :oauth do
    # As this is borrowed from OpenID, the specification says we must also support
    # POST for the userinfo endpoint:
    # https://openid.net/specs/openid-connect-core-1_0.html#UserInfo
    match 'userinfo', via: [:get, :post], to: 'userinfo#show', defaults: { format: 'json' }
  end

  scope path: '.well-known' do
    scope module: :well_known do
      get 'oauth-authorization-server', to: 'oauth_metadata#show', as: :oauth_metadata, defaults: { format: 'json' }
      get 'host-meta', to: 'host_meta#show', as: :host_meta
      get 'nodeinfo', to: 'node_info#index', as: :nodeinfo, defaults: { format: 'json' }
      get 'webfinger', to: 'webfinger#show', as: :webfinger
    end
    get 'change-password', to: redirect('/auth/edit'), as: nil
    get 'proxy', to: redirect { |_, request| "/authorize_interaction?#{request.params.to_query}" }, as: nil
  end

  get '/nodeinfo/2.0', to: 'well_known/node_info#show', as: :nodeinfo_schema

  get 'manifest', to: 'manifests#show', defaults: { format: 'json' }
  get 'intent', to: 'intents#show'
  get 'custom.css', to: 'custom_css#show'
  resources :custom_css, only: :show, path: :css

  get 'remote_interaction_helper', to: 'remote_interaction_helper#index'

  resource :instance_actor, path: 'actor', only: [:show] do
    scope module: :activitypub do
      resource :inbox, only: [:create]
      resource :outbox, only: [:show]
    end
  end

  get '/invite/:invite_code', constraints: ->(req) { req.format == :json }, to: 'api/v1/invites#show'

  devise_scope :user do
    get '/invite/:invite_code', to: 'auth/registrations#new', as: :public_invite

    resource :unsubscribe, only: [:show, :create], controller: :mail_subscriptions

    namespace :auth do
      resource :setup, only: [:show, :update], controller: :setup
      resource :challenge, only: [:create]
      get 'sessions/security_key_options', to: 'sessions#webauthn_options'
      post 'captcha_confirmation', to: 'confirmations#confirm_captcha', as: :captcha_confirmation
    end
  end

  scope module: :auth do
    devise_for :users, path: 'auth', format: false
  end

  with_options constraints: ->(req) { req.format.nil? || req.format.html? } do
    get '/users/:username', to: redirect_with_vary('/@%{username}')
    get '/users/:username/following', to: redirect_with_vary('/@%{username}/following')
    get '/users/:username/followers', to: redirect_with_vary('/@%{username}/followers')
    get '/users/:username/statuses/:id', to: redirect_with_vary('/@%{username}/%{id}')
  end

  get '/authorize_follow', to: redirect { |_, request| "/authorize_interaction?#{request.params.to_query}" }

  resources :accounts, path: 'users', only: [:show], param: :username do
    resources :statuses, only: [:show] do
      member do
        get :activity
        get :embed
      end

      resources :replies, only: [:index], module: :activitypub
      resources :likes, only: [:index], module: :activitypub
      resources :shares, only: [:index], module: :activitypub
    end

    resources :followers, only: [:index], controller: :follower_accounts
    resources :following, only: [:index], controller: :following_accounts

    scope module: :activitypub do
      resource :outbox, only: [:show]
      resource :inbox, only: [:create]
      resources :collections, only: [:show]
      resource :followers_synchronization, only: [:show]
    end
  end

  resource :inbox, only: [:create], module: :activitypub

  constraints(encoded_path: /%40.*/) do
    get '/:encoded_path', to: redirect { |params|
      "/#{params[:encoded_path].gsub('%40', '@')}"
    }
  end

  constraints(username: %r{[^@/.]+}) do
    with_options to: 'accounts#show' do
      get '/@:username', as: :short_account
      get '/@:username/with_replies', as: :short_account_with_replies
      get '/@:username/media', as: :short_account_media
      get '/@:username/tagged/:tag', as: :short_account_tag
    end
  end

  constraints(account_username: %r{[^@/.]+}) do
    get '/@:account_username/following', to: 'following_accounts#index'
    get '/@:account_username/followers', to: 'follower_accounts#index'
    get '/@:account_username/:id', to: 'statuses#show', as: :short_account_status
    get '/@:account_username/:id/embed', to: 'statuses#embed', as: :embed_short_account_status
  end

  get '/@:username_with_domain/(*any)', to: 'home#index', constraints: { username_with_domain: %r{([^/])+?} }, as: :account_with_domain, format: false
  get '/settings', to: redirect('/settings/profile')

  draw(:settings)

  namespace :disputes do
    resources :strikes, only: [:show, :index] do
      resource :appeal, only: [:create]
    end
  end

  namespace :redirect do
    resources :accounts, only: :show
    resources :statuses, only: :show
  end

  resources :media, only: [:show] do
    get :player
  end

  resources :tags,   only: [:show]
  resources :emojis, only: [:show]
  resources :invites, only: [:index, :create, :destroy]
  resources :filters, except: [:show] do
    resources :statuses, only: [:index], controller: 'filters/statuses' do
      collection do
        post :batch
      end
    end
  end

  resource :relationships, only: [:show, :update]
  resources :severed_relationships, only: [:index] do
    member do
      constraints(format: :csv) do
        get :followers
        get :following
      end
    end
  end
  resource :statuses_cleanup, controller: :statuses_cleanup, only: [:show, :update]

  get '/media_proxy/:id/(*any)', to: 'media_proxy#show', as: :media_proxy, format: false
  get '/backups/:id/download', to: 'backups#download', as: :download_backup, format: false

  resource :authorize_interaction, only: [:show]
  resource :share, only: [:show]

  draw(:admin)

  get '/admin', to: redirect('/admin/dashboard', status: 302)

  draw(:api)

  draw(:web_app)

  get '/web/(*any)', to: redirect('/%{any}', status: 302), as: :web, defaults: { any: '' }, format: false
  get '/about',      to: 'about#show'
  get '/about/more', to: redirect('/about')

  get '/privacy-policy',   to: 'privacy#show', as: :privacy_policy
  get '/terms-of-service', to: 'terms_of_service#show', as: :terms_of_service
  get '/terms',            to: redirect('/terms-of-service')

  match '/', via: [:post, :put, :patch, :delete], to: 'application#raise_not_found', format: false
  match '*unmatched_route', via: :all, to: 'application#raise_not_found', format: false
end

app/controllers/api/v1/filters_controller.rb
# frozen_string_literal: true

class Api::V1::FiltersController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read, :'read:filters' }, only: [:index, :show]
  before_action -> { doorkeeper_authorize! :write, :'write:filters' }, except: [:index, :show]
  before_action :require_user!
  before_action :set_filters, only: :index
  before_action :set_filter, only: [:show, :update, :destroy]

  def index
    render json: @filters, each_serializer: REST::V1::FilterSerializer
  end

  def show
    render json: @filter, serializer: REST::V1::FilterSerializer
  end

  def create
    ApplicationRecord.transaction do
      filter_category = current_account.custom_filters.create!(filter_params)
      @filter = filter_category.keywords.create!(keyword_params)
    end

    render json: @filter, serializer: REST::V1::FilterSerializer
  end

  def update
    ApplicationRecord.transaction do
      @filter.update!(keyword_params)
      @filter.custom_filter.assign_attributes(filter_params)
      raise Mastodon::ValidationError, I18n.t('filters.errors.deprecated_api_multiple_keywords') if @filter.custom_filter.changed? && @filter.custom_filter.keywords.count > 1

      @filter.custom_filter.save!
    end

    render json: @filter, serializer: REST::V1::FilterSerializer
  end

  def destroy
    @filter.destroy!
    render_empty
  end

  private

  def set_filters
    @filters = CustomFilterKeyword.includes(:custom_filter).where(custom_filter: { account: current_account })
  end

  def set_filter
    @filter = CustomFilterKeyword.includes(:custom_filter).where(custom_filter: { account: current_account }).find(params[:id])
  end

  def resource_params
    params.permit(:phrase, :expires_in, :irreversible, :whole_word, context: [])
  end

  def filter_params
    resource_params.slice(:phrase, :expires_in, :irreversible, :context)
  end

  def keyword_params
    resource_params.slice(:phrase, :whole_word)
  end
end

app/controllers/api/v2/filters/keywords_controller.rb
# frozen_string_literal: true

class Api::V2::Filters::KeywordsController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read, :'read:filters' }, only: [:index, :show]
  before_action -> { doorkeeper_authorize! :write, :'write:filters' }, except: [:index, :show]
  before_action :require_user!

  before_action :set_keywords, only: :index
  before_action :set_keyword, only: [:show, :update, :destroy]

  def index
    render json: @keywords, each_serializer: REST::FilterKeywordSerializer
  end

  def show
    render json: @keyword, serializer: REST::FilterKeywordSerializer
  end

  def create
    @keyword = current_account.custom_filters.find(params[:filter_id]).keywords.create!(resource_params)

    render json: @keyword, serializer: REST::FilterKeywordSerializer
  end

  def update
    @keyword.update!(resource_params)

    render json: @keyword, serializer: REST::FilterKeywordSerializer
  end

  def destroy
    @keyword.destroy!
    render_empty
  end

  private

  def set_keywords
    filter = current_account.custom_filters.includes(:keywords).find(params[:filter_id])
    @keywords = filter.keywords
  end

  def set_keyword
    @keyword = CustomFilterKeyword.includes(:custom_filter).where(custom_filter: { account: current_account }).find(params[:id])
  end

  def resource_params
    params.permit(:keyword, :whole_word)
  end
end

app/controllers/api/v2/filters/statuses_controller.rb
# frozen_string_literal: true

class Api::V2::Filters::StatusesController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read, :'read:filters' }, only: [:index, :show]
  before_action -> { doorkeeper_authorize! :write, :'write:filters' }, except: [:index, :show]
  before_action :require_user!

  before_action :set_status_filters, only: :index
  before_action :set_status_filter, only: [:show, :destroy]

  def index
    render json: @status_filters, each_serializer: REST::FilterStatusSerializer
  end

  def show
    render json: @status_filter, serializer: REST::FilterStatusSerializer
  end

  def create
    @status_filter = current_account.custom_filters.find(params[:filter_id]).statuses.create!(resource_params)

    render json: @status_filter, serializer: REST::FilterStatusSerializer
  end

  def destroy
    @status_filter.destroy!
    render_empty
  end

  private

  def set_status_filters
    filter = current_account.custom_filters.includes(:statuses).find(params[:filter_id])
    @status_filters = filter.statuses
  end

  def set_status_filter
    @status_filter = CustomFilterStatus.includes(:custom_filter).where(custom_filter: { account: current_account }).find(params[:id])
  end

  def resource_params
    params.permit(:status_id)
  end
end

app/controllers/api/v2/filters_controller.rb
# frozen_string_literal: true

class Api::V2::FiltersController < Api::BaseController
  before_action -> { doorkeeper_authorize! :read, :'read:filters' }, only: [:index, :show]
  before_action -> { doorkeeper_authorize! :write, :'write:filters' }, except: [:index, :show]
  before_action :require_user!
  before_action :set_filters, only: :index
  before_action :set_filter, only: [:show, :update, :destroy]

  def index
    render json: @filters, each_serializer: REST::FilterSerializer, rules_requested: true
  end

  def show
    render json: @filter, serializer: REST::FilterSerializer, rules_requested: true
  end

  def create
    @filter = current_account.custom_filters.create!(resource_params)

    render json: @filter, serializer: REST::FilterSerializer, rules_requested: true
  end

  def update
    @filter.update!(resource_params)

    render json: @filter, serializer: REST::FilterSerializer, rules_requested: true
  end

  def destroy
    @filter.destroy!
    render_empty
  end

  private

  def set_filters
    @filters = current_account.custom_filters.includes(:keywords, :statuses)
  end

  def set_filter
    @filter = current_account.custom_filters.find(params[:id])
  end

  def resource_params
    params.permit(:title, :expires_in, :filter_action, context: [], keywords_attributes: [:id, :keyword, :whole_word, :_destroy])
  end
end

app/controllers/filters/statuses_controller.rb
# frozen_string_literal: true

class Filters::StatusesController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
  before_action :set_filter
  before_action :set_status_filters

  PER_PAGE = 20

  def index
    @status_filter_batch_action = Form::StatusFilterBatchAction.new
  end

  def batch
    @status_filter_batch_action = Form::StatusFilterBatchAction.new(status_filter_batch_action_params.merge(current_account: current_account, filter_id: params[:filter_id], type: action_from_button))
    @status_filter_batch_action.save!
  rescue ActionController::ParameterMissing
    flash[:alert] = I18n.t('admin.statuses.no_status_selected')
  ensure
    redirect_to edit_filter_path(@filter)
  end

  private

  def set_filter
    @filter = current_account.custom_filters.find(params[:filter_id])
  end

  def set_status_filters
    @status_filters = @filter.statuses.preload(:status).page(params[:page]).per(PER_PAGE)
  end

  def status_filter_batch_action_params
    params.expect(form_status_filter_batch_action: [status_filter_ids: []])
  end

  def action_from_button
    'remove' if params[:remove]
  end
end

app/controllers/filters_controller.rb
# frozen_string_literal: true

class FiltersController < ApplicationController
  layout 'admin'

  before_action :authenticate_user!
  before_action :set_filter, only: [:edit, :update, :destroy]

  def index
    @filters = current_account.custom_filters.includes(:keywords, :statuses).order(:phrase)
  end

  def new
    @filter = current_account.custom_filters.build(action: :warn)
    @filter.keywords.build
  end

  def edit; end

  def create
    @filter = current_account.custom_filters.build(resource_params)

    if @filter.save
      redirect_to filters_path
    else
      render :new
    end
  end

  def update
    if @filter.update(resource_params)
      redirect_to filters_path
    else
      render :edit
    end
  end

  def destroy
    @filter.destroy
    redirect_to filters_path
  end

  private

  def set_filter
    @filter = current_account.custom_filters.find(params[:id])
  end

  def resource_params
    params.expect(custom_filter: [:title, :expires_in, :filter_action, context: [], keywords_attributes: [[:id, :keyword, :whole_word, :_destroy]]])
  end
end

app/helpers/admin/filter_helper.rb
# frozen_string_literal: true

module Admin::FilterHelper
  FILTERS = [
    AccountFilter::KEYS,
    CustomEmojiFilter::KEYS,
    ReportFilter::KEYS,
    Trends::TagFilter::KEYS,
    Trends::PreviewCardProviderFilter::KEYS,
    Trends::PreviewCardFilter::KEYS,
    Trends::StatusFilter::KEYS,
    InstanceFilter::KEYS,
    InviteFilter::KEYS,
    RelationshipFilter::KEYS,
    AnnouncementFilter::KEYS,
    Admin::ActionLogFilter::KEYS,
    Admin::StatusFilter::KEYS,
  ].flatten.freeze

  def filter_link_to(text, link_to_params, link_class_params = link_to_params)
    new_url   = filtered_url_for(link_to_params)
    new_class = filtered_url_for(link_class_params)

    link_to text, new_url, class: filter_link_class(new_class)
  end

  def table_link_to(icon, text, path, **options)
    link_to safe_join([material_symbol(icon), text]), path, options.merge(class: 'table-action-link')
  end

  def selected?(more_params)
    new_url = filtered_url_for(more_params)
    filter_link_class(new_url) == 'selected'
  end

  private

  def filter_params(more_params)
    controller_request_params.merge(more_params)
  end

  def filter_link_class(new_url)
    filtered_url_for(controller_request_params) == new_url ? 'selected' : ''
  end

  def filtered_url_for(url_params)
    url_for filter_params(url_params)
  end

  def controller_request_params
    params.permit(FILTERS)
  end
end

app/helpers/filters_helper.rb
# frozen_string_literal: true

module FiltersHelper
  def filter_action_label(action)
    safe_join(
      [
        t("simple_form.labels.filters.actions.#{action}"),
        content_tag(:span, t("simple_form.hints.filters.actions.#{action}"), class: 'hint'),
      ]
    )
  end
end

app/views/filters/_filter.html.haml
.filters-list__item{ class: [filter.expired? && 'expired'] }
  = link_to edit_filter_path(filter), class: 'filters-list__item__title' do
    = filter.title

    - if filter.expires?
      .expiration{ title: t('filters.index.expires_on', date: l(filter.expires_at)) }
        - if filter.expired?
          = t('invites.expired')
        - else
          = t('filters.index.expires_in', distance: distance_of_time_in_words_to_now(filter.expires_at))

  .filters-list__item__permissions
    %ul.permissions-list
      - unless filter.keywords.empty?
        %li.permissions-list__item
          .permissions-list__item__icon
            = material_symbol('format_paragraph')
          .permissions-list__item__text
            .permissions-list__item__text__title
              = t('filters.index.keywords', count: filter.keywords.size)
            .permissions-list__item__text__type
              - keywords = filter.keywords.map(&:keyword)
              - keywords = keywords.take(5) + ['…'] if keywords.size > 5 # TODO
              = keywords.join(', ')
      - unless filter.statuses.empty?
        %li.permissions-list__item
          .permissions-list__item__icon
            = material_symbol('chat')
          .permissions-list__item__text
            .permissions-list__item__text__title
              = t('filters.index.statuses', count: filter.statuses.size)
            .permissions-list__item__text__type
              = t('filters.index.statuses_long', count: filter.statuses.size)

  .announcements-list__item__action-bar
    .announcements-list__item__meta
      = t('filters.index.contexts', contexts: filter.context.map { |context| I18n.t("filters.contexts.#{context}") }.join(', '))

    %div
      = table_link_to 'edit', t('filters.edit.title'), edit_filter_path(filter)
      = table_link_to 'close', t('filters.index.delete'), filter_path(filter), method: :delete, data: { confirm: t('admin.accounts.are_you_sure') }

app/views/filters/_filter_fields.html.haml
.fields-row
  .fields-row__column.fields-row__column-6.fields-group
    = f.input :title,
              as: :string,
              hint: false,
              wrapper: :with_label
  .fields-row__column.fields-row__column-6.fields-group
    = f.input :expires_in,
              collection: CustomFilter::EXPIRATION_DURATIONS.map(&:to_i),
              include_blank: I18n.t('invites.expires_in_prompt'),
              label_method: ->(i) { I18n.t("invites.expires_in.#{i}") },
              wrapper: :with_label

.fields-group
  = f.input :context,
            as: :check_boxes,
            collection_wrapper_tag: 'ul',
            collection: CustomFilter::VALID_CONTEXTS,
            include_blank: false,
            item_wrapper_tag: 'li',
            label_method: ->(context) { I18n.t("filters.contexts.#{context}") },
            wrapper: :with_block_label

%hr.spacer/

.fields-group
  = f.input :filter_action,
            as: :radio_buttons,
            collection: %i(warn hide),
            hint: t('simple_form.hints.filters.action'),
            include_blank: false,
            label_method: ->(action) { filter_action_label(action) },
            required: true,
            wrapper: :with_block_label

%hr.spacer/

- unless f.object.statuses.empty?
  %h4= t('filters.edit.statuses')

  %p.muted-hint= t('filters.edit.statuses_hint_html', path: filter_statuses_path(f.object))

  %hr.spacer/

%h4= t('filters.edit.keywords')

.table-wrapper
  %table.table.keywords-table
    %thead
      %tr
        %th= t('simple_form.labels.defaults.phrase')
        %th= t('simple_form.labels.defaults.whole_word')
        %th
    %tbody
      = f.simple_fields_for :keywords do |keyword|
        = render 'keyword_fields', f: keyword
    %tfoot
      %tr
        %td{ colspan: 3 }
          = link_to_add_association f, :keywords, class: 'table-action-link', partial: 'keyword_fields', 'data-association-insertion-node': '.keywords-table tbody', 'data-association-insertion-method': 'append' do
            = safe_join([material_symbol('add'), t('filters.edit.add_keyword')])

app/views/filters/_keyword_fields.html.haml
%tr.nested-fields
  %td= f.input :keyword, as: :string
  %td
    .label_input__wrapper= f.input_field :whole_word
  %td
    = f.hidden_field :id if f.object&.persisted? # Required so Rails doesn't put the field outside of the <tr/>
    = link_to_remove_association(f, class: 'table-action-link') do
      = safe_join([material_symbol('close'), t('filters.index.delete')])

app/views/filters/edit.html.haml
- content_for :page_title do
  = t('filters.edit.title')

= simple_form_for @filter, url: filter_path(@filter), method: :put do |f|
  = render 'filter_fields', f: f

  .actions
    = f.button :button, t('generic.save_changes'), type: :submit

app/views/filters/index.html.haml
- content_for :page_title do
  = t('filters.index.title')

- content_for :heading_actions do
  = link_to t('filters.new.title'), new_filter_path, class: 'button'

- if @filters.empty?
  .muted-hint.center-text= t 'filters.index.empty'
- else
  .applications-list
    = render partial: 'filter', collection: @filters

app/views/filters/new.html.haml
- content_for :page_title do
  = t('filters.new.title')

= simple_form_for @filter, url: filters_path do |f|
  = render 'filter_fields', f: f

  .actions
    = f.button :button, t('filters.new.save'), type: :submit